# Generated by Django 3.0.2 on 2020-01-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200115_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='people',
            new_name='persons',
        ),
    ]
