# Generated by Django 3.0.2 on 2020-01-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefits',
            new_name='Benefit',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
    ]
