# Generated by Django 3.0.2 on 2020-01-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringcategory',
            name='image',
        ),
    ]
