# Generated by Django 3.0.2 on 2020-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_remove_cateringcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringproduct',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
