# Generated by Django 3.0.2 on 2020-01-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('number_of_persons', models.IntegerField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
