# Generated by Django 3.0.2 on 2020-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, default='Ukraine', max_length=100),
        ),
    ]
